### PR TITLE
Adding more testing pages

### PR DESCRIPTION
**Pull request by pedroha**
Create testing pages for the logo animation for troubleshooting

### CODE REVIEW

**Comment by deepdeepdot** [comment]
So far, we got 12 working, 11 not working. The only difference is the meta tag:
12: ok
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

11: not ok
    <meta name="viewport" content="width=device-width" />

We  removed the viewport tag for index.2.html, but was not enough. css-filter with css variable properties look fragile for mobile.

**Comment by pedroha** [comment]
Unbelievable. It works for ff.html (where we try to hue rotate genspace logo, but fails in mobile) but the same animation is not working in fff.html (where we removed the animation code for the genspace logo - which wasn't working for mobile anyway)

**Comment by pedroha** [comment]
For ios, the filter animation does not seem as reliable as in desktop.
TODO: check same experience on Android.

**Comment by pedroha** [comment]
Yep! Keyframe animation with infinite loop working for both SVG and PNG logos.

Eureka!!!

**Comment by pedroha** [comment]
Logo animation working fine. Transitions get yanked in chrome/brave, but smooth in Safari/Firefox. It may be due to memory?

Fix with keyframe animation has been incorporated, closing this PR

**Pull request closed without merging**
